"""empty message

Revision ID: 01a2236fa4c9
Revises: edf87de3a295
Create Date: 2021-10-14 10:09:00.055694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a2236fa4c9'
down_revision = 'edf87de3a295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_team_partner_partner', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_team_leader_partner'), 'partner', ['leader'], ['id'])
        batch_op.drop_column('partner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_team_leader_partner'), type_='foreignkey')
        batch_op.create_foreign_key('fk_team_partner_partner', 'partner', ['partner'], ['id'])
        batch_op.drop_column('leader')

    # ### end Alembic commands ###
