"""empty message

Revision ID: 0517a276cfc3
Revises: 
Create Date: 2022-02-16 11:56:15.464642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0517a276cfc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_category'))
    )
    with op.batch_alter_table('company_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_category_name'), ['name'], unique=False)

    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currency'))
    )
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currency_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_currency_name'), ['name'], unique=True)

    op.create_table('database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database'))
    )
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_name'), ['name'], unique=False)

    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model')),
    sa.UniqueConstraint('slug', name=op.f('uq_model_slug'))
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_name'), ['name'], unique=False)

    op.create_table('module_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_category'))
    )
    op.create_table('partner_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_title'))
    )
    with op.batch_alter_table('partner_title', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_title_name'), ['name'], unique=False)

    op.create_table('recurring_plan',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_plan'))
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage')),
    sa.UniqueConstraint('position', name=op.f('uq_stage_position'))
    )
    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_name'), ['name'], unique=True)

    op.create_table('access',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('write', sa.Boolean(), nullable=True),
    sa.Column('create', sa.Boolean(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_access_model_id_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access')),
    sa.UniqueConstraint('slug', name=op.f('uq_access_slug'))
    )
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_name'), ['name'], unique=True)

    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('domain_name', sa.String(length=120), nullable=True),
    sa.Column('report_header', sa.Text(), nullable=True),
    sa.Column('report_footer', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('street2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_address', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('mobile_no', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['company_category.id'], name=op.f('fk_company_category_id_company_category')),
    sa.ForeignKeyConstraint(['database_id'], ['database.id'], name=op.f('fk_company_database_id_database')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company'))
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_domain_name'), ['domain_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_mobile_no'), ['mobile_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_website'), ['website'], unique=False)

    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('calling_code', sa.String(length=120), nullable=True),
    sa.Column('currency_name', sa.String(length=60), nullable=True),
    sa.Column('currency_alphabetic_code', sa.String(length=60), nullable=True),
    sa.Column('currency_numeric_code', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name=op.f('fk_country_currency_id_currency')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country'))
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_calling_code'), ['calling_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_country_currency_alphabetic_code'), ['currency_alphabetic_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_currency_name'), ['currency_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_currency_numeric_code'), ['currency_numeric_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_languages'), ['languages'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_name'), ['name'], unique=True)

    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technical_name', sa.String(length=128), nullable=True),
    sa.Column('official_name', sa.String(length=128), nullable=True),
    sa.Column('bp_name', sa.String(length=128), nullable=True),
    sa.Column('installed_version', sa.String(length=60), nullable=True),
    sa.Column('auto_install', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.String(length=350), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_groups_api', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['module_category.id'], name=op.f('fk_module_category_id_module_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module'))
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_bp_name'), ['bp_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_official_name'), ['official_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_technical_name'), ['technical_name'], unique=False)

    op.create_table('ModuleModels',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_ModuleModels_model_id_model')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('fk_ModuleModels_module_id_module')),
    sa.PrimaryKeyConstraint('module_id', 'model_id', name=op.f('pk_ModuleModels'))
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('geonameid', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_city_country_id_country')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city')),
    sa.UniqueConstraint('geonameid', name=op.f('uq_city_geonameid'))
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_name'), ['name'], unique=False)

    op.create_table('group',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.Column('access_rights_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('fk_group_module_id_module')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group')),
    sa.UniqueConstraint('slug', name=op.f('uq_group_slug'))
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_name'), ['name'], unique=False)

    op.create_table('AccessRights',
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('access_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], name=op.f('fk_AccessRights_access_id_access')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_AccessRights_group_id_group')),
    sa.PrimaryKeyConstraint('group_id', 'access_id', name=op.f('pk_AccessRights'))
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('function', sa.String(length=60), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_individual', sa.Boolean(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('phone_no', sa.String(length=120), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=120), nullable=True),
    sa.Column('postal_address', sa.String(length=120), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_tenant', sa.Boolean(), nullable=True),
    sa.Column('tax_id', sa.String(length=60), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_partner_city_id_city')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_partner_company_id_company')),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_partner_country_id_country')),
    sa.ForeignKeyConstraint(['parent_id'], ['partner.id'], name=op.f('fk_partner_parent_id_partner')),
    sa.ForeignKeyConstraint(['title_id'], ['partner_title.id'], name=op.f('fk_partner_title_id_partner_title')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner')),
    sa.UniqueConstraint('slug', name=op.f('uq_partner_slug'))
    )
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_function'), ['function'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_phone_no'), ['phone_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_postal_address'), ['postal_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_tax_id'), ['tax_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_website'), ['website'], unique=False)

    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['partner.id'], name=op.f('fk_organization_id_partner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['leader'], ['partner.id'], name=op.f('fk_team_leader_partner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_token'), ['token'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=120), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('user_type', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_users_company_id_company')),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_users_partner_id_partner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('slug', name=op.f('uq_users_slug'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_token'), ['token'], unique=True)

    op.create_table('UserGroup',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_UserGroup_group_id_group')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_UserGroup_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_UserGroup'))
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('referred_by', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=15), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('expected_revenue', sa.String(length=60), nullable=True),
    sa.Column('date_open', sa.DateTime(), nullable=True),
    sa.Column('expected_closing', sa.DateTime(), nullable=True),
    sa.Column('partner_email', sa.String(length=120), nullable=True),
    sa.Column('partner_phone', sa.String(length=60), nullable=True),
    sa.Column('partner_currency', sa.String(length=10), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_lead_company_id_company')),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_lead_partner_id_partner')),
    sa.ForeignKeyConstraint(['plan_id'], ['recurring_plan.id'], name=op.f('fk_lead_plan_id_recurring_plan')),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_lead_stage_id_stage')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lead_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead')),
    sa.UniqueConstraint('slug', name=op.f('uq_lead_slug'))
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_partner_currency'), ['partner_currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_partner_email'), ['partner_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_partner_phone'), ['partner_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_priority'), ['priority'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_name'), ['name'], unique=False)

    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['partner.id'], name=op.f('fk_team_member_member_partner')),
    sa.ForeignKeyConstraint(['team'], ['team.id'], name=op.f('fk_team_member_team_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_member'))
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name=op.f('fk_note_lead_id_lead')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_note_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('team_member')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_name'))

    op.drop_table('task')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_priority'))
        batch_op.drop_index(batch_op.f('ix_lead_partner_phone'))
        batch_op.drop_index(batch_op.f('ix_lead_partner_email'))
        batch_op.drop_index(batch_op.f('ix_lead_partner_currency'))
        batch_op.drop_index(batch_op.f('ix_lead_name'))

    op.drop_table('lead')
    op.drop_table('UserGroup')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_token'))
        batch_op.drop_index(batch_op.f('ix_users_country_code'))

    op.drop_table('users')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_token'))
        batch_op.drop_index(batch_op.f('ix_team_name'))

    op.drop_table('team')
    op.drop_table('organization')
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_website'))
        batch_op.drop_index(batch_op.f('ix_partner_title'))
        batch_op.drop_index(batch_op.f('ix_partner_tax_id'))
        batch_op.drop_index(batch_op.f('ix_partner_postal_code'))
        batch_op.drop_index(batch_op.f('ix_partner_postal_address'))
        batch_op.drop_index(batch_op.f('ix_partner_phone_no'))
        batch_op.drop_index(batch_op.f('ix_partner_name'))
        batch_op.drop_index(batch_op.f('ix_partner_function'))
        batch_op.drop_index(batch_op.f('ix_partner_email'))
        batch_op.drop_index(batch_op.f('ix_partner_company_name'))

    op.drop_table('partner')
    op.drop_table('AccessRights')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_name'))

    op.drop_table('group')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_name'))

    op.drop_table('city')
    op.drop_table('ModuleModels')
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_technical_name'))
        batch_op.drop_index(batch_op.f('ix_module_official_name'))
        batch_op.drop_index(batch_op.f('ix_module_bp_name'))

    op.drop_table('module')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_name'))
        batch_op.drop_index(batch_op.f('ix_country_languages'))
        batch_op.drop_index(batch_op.f('ix_country_currency_numeric_code'))
        batch_op.drop_index(batch_op.f('ix_country_currency_name'))
        batch_op.drop_index(batch_op.f('ix_country_currency_alphabetic_code'))
        batch_op.drop_index(batch_op.f('ix_country_code'))
        batch_op.drop_index(batch_op.f('ix_country_calling_code'))

    op.drop_table('country')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_website'))
        batch_op.drop_index(batch_op.f('ix_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_mobile_no'))
        batch_op.drop_index(batch_op.f('ix_company_email'))
        batch_op.drop_index(batch_op.f('ix_company_domain_name'))

    op.drop_table('company')
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_name'))

    op.drop_table('access')
    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_name'))

    op.drop_table('stage')
    op.drop_table('recurring_plan')
    with op.batch_alter_table('partner_title', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_title_name'))

    op.drop_table('partner_title')
    op.drop_table('module_category')
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_name'))

    op.drop_table('model')
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_name'))

    op.drop_table('database')
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currency_name'))
        batch_op.drop_index(batch_op.f('ix_currency_code'))

    op.drop_table('currency')
    with op.batch_alter_table('company_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_category_name'))

    op.drop_table('company_category')
    # ### end Alembic commands ###
