"""empty message

Revision ID: 0648a3fb3b4b
Revises: aeae0784cd62
Create Date: 2022-05-03 12:55:07.457867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0648a3fb3b4b'
down_revision = 'aeae0784cd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax', sa.String(length=100), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_tax'), ['tax'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_tax'))
        batch_op.drop_column('tax')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('tax')

    # ### end Alembic commands ###
