"""empty message

Revision ID: 0f31852cbd17
Revises: 3fa1c9f75fe7
Create Date: 2021-09-29 10:48:20.525455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f31852cbd17'
down_revision = '3fa1c9f75fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_partner_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_title'))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
