"""empty message

Revision ID: 16f488b064e1
Revises: 3de1222b74d4
Create Date: 2021-09-24 21:18:00.198682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f488b064e1'
down_revision = '3de1222b74d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint('fk_company_contact_id_contact', type_='foreignkey')
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_contact_company_id_company'), 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contact_company_id_company'), type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_company_contact_id_contact', 'contact', ['contact_id'], ['id'])

    # ### end Alembic commands ###
