"""empty message

Revision ID: 17e591a88f12
Revises: 
Create Date: 2022-01-24 09:16:05.118979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e591a88f12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model'))
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_name'), ['name'], unique=False)

    op.create_table('access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_access_model_id_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access'))
    )
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_name'), ['name'], unique=True)

    op.create_table('AccessRights',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], name=op.f('fk_AccessRights_access_id_access')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_AccessRights_group_id_group')),
    sa.PrimaryKeyConstraint('group_id', 'access_id', name=op.f('pk_AccessRights'))
    )
    with op.batch_alter_table('user_right', schema=None) as batch_op:
        batch_op.drop_index('ix_user_right_access_right')

    op.drop_table('user_right')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_right',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_right', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user_right')
    )
    with op.batch_alter_table('user_right', schema=None) as batch_op:
        batch_op.create_index('ix_user_right_access_right', ['access_right'], unique=False)

    op.drop_table('AccessRights')
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_name'))

    op.drop_table('access')
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_name'))

    op.drop_table('model')
    # ### end Alembic commands ###
