"""empty message

Revision ID: 256ff5f1c271
Revises: e9a24861991c
Create Date: 2021-10-06 14:42:15.505592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256ff5f1c271'
down_revision = 'e9a24861991c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_phone', sa.String(length=60), nullable=True))
        batch_op.drop_index('ix_lead_partner_currency')
        batch_op.drop_index('ix_lead_partner_name')
        batch_op.create_index(batch_op.f('ix_lead_partner_phone'), ['partner_phone'], unique=False)
        batch_op.drop_column('partner_currency')
        batch_op.drop_column('partner_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_name', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('partner_currency', sa.VARCHAR(length=60), nullable=True))
        batch_op.drop_index(batch_op.f('ix_lead_partner_phone'))
        batch_op.create_index('ix_lead_partner_name', ['partner_name'], unique=False)
        batch_op.create_index('ix_lead_partner_currency', ['partner_currency'], unique=False)
        batch_op.drop_column('partner_phone')

    # ### end Alembic commands ###
