"""empty message

Revision ID: 34679c34afbc
Revises: 564ad9e17d3b
Create Date: 2021-09-30 11:35:14.133024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34679c34afbc'
down_revision = '564ad9e17d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.String(length=120), nullable=True))
        batch_op.drop_index('ix_partner_city')
        batch_op.drop_index('ix_partner_county_id')
        batch_op.create_index(batch_op.f('ix_partner_city_id'), ['city_id'], unique=False)
        batch_op.drop_column('county_id')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('county_id', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_partner_city_id'))
        batch_op.create_index('ix_partner_county_id', ['county_id'], unique=False)
        batch_op.create_index('ix_partner_city', ['city'], unique=False)
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###
