"""empty message

Revision ID: 3a2d6984adee
Revises: 17e591a88f12
Create Date: 2022-01-24 10:30:11.362813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2d6984adee'
down_revision = '17e591a88f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_access_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_access_slug'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
