"""empty message

Revision ID: 3a3ba2e8fbe9
Revises: 0648a3fb3b4b
Create Date: 2022-05-05 13:27:11.543254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3ba2e8fbe9'
down_revision = '0648a3fb3b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
