"""empty message

Revision ID: 3ce2db8587c0
Revises: 55a7c8d64f78
Create Date: 2022-01-24 16:32:17.362463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce2db8587c0'
down_revision = '55a7c8d64f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('write', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.drop_column('delete')
        batch_op.drop_column('create')
        batch_op.drop_column('write')
        batch_op.drop_column('read')

    # ### end Alembic commands ###
