"""empty message

Revision ID: 3de1222b74d4
Revises: a21a226993f3
Create Date: 2021-09-24 16:00:16.281341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de1222b74d4'
down_revision = 'a21a226993f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_category'))
    )
    with op.batch_alter_table('company_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_category_name'), ['name'], unique=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('street2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('mobile_no', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_company_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_mobile_no'), ['mobile_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_website'), ['website'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_company_contact_id_contact'), 'contact', ['contact_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_company_category_id_company_category'), 'company_category', ['category_id'], ['id'])

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_individual', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_company', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('is_company')
        batch_op.drop_column('is_individual')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_company_category_id_company_category'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_company_contact_id_contact'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_company_website'))
        batch_op.drop_index(batch_op.f('ix_company_mobile_no'))
        batch_op.drop_index(batch_op.f('ix_company_email'))
        batch_op.drop_column('category_id')
        batch_op.drop_column('website')
        batch_op.drop_column('mobile_no')
        batch_op.drop_column('email')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('postal_address')
        batch_op.drop_column('county')
        batch_op.drop_column('city')
        batch_op.drop_column('street2')
        batch_op.drop_column('street')
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('company_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_category_name'))

    op.drop_table('company_category')
    # ### end Alembic commands ###
