"""empty message

Revision ID: 3e139417df1f
Revises: 6ef4c4f7e3cd
Create Date: 2022-03-19 22:10:35.987237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e139417df1f'
down_revision = '6ef4c4f7e3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.drop_constraint('fk_activity_type_activity_type', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_activity_activity_type_activity_type'), 'activity_type', ['activity_type'], ['id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_activity_activity_type_activity_type'), type_='foreignkey')
        batch_op.create_foreign_key('fk_activity_type_activity_type', 'activity_type', ['type'], ['id'])
        batch_op.drop_column('activity_type')

    # ### end Alembic commands ###
