"""empty message

Revision ID: 3fa1c9f75fe7
Revises: d98f12a07463
Create Date: 2021-09-28 21:32:11.027580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa1c9f75fe7'
down_revision = 'd98f12a07463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('function', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_partner_function'), ['function'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_function'))
        batch_op.drop_column('function')

    # ### end Alembic commands ###
