"""empty message

Revision ID: 40bcc0e69b8b
Revises: 0517a276cfc3
Create Date: 2022-02-16 16:05:01.972879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bcc0e69b8b'
down_revision = '0517a276cfc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('models_api', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('models_api')

    # ### end Alembic commands ###
