"""empty message

Revision ID: 42cd9caf7bde
Revises: 
Create Date: 2021-09-19 21:15:16.212163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cd9caf7bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database'))
    )
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_name'), ['name'], unique=False)

    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technical_name', sa.String(length=128), nullable=True),
    sa.Column('official_name', sa.String(length=128), nullable=True),
    sa.Column('bp_name', sa.String(length=128), nullable=True),
    sa.Column('installed_version', sa.String(length=60), nullable=True),
    sa.Column('auto_install', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.String(length=350), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module'))
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_bp_name'), ['bp_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_official_name'), ['official_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_technical_name'), ['technical_name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('phone_no', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone_no'), ['phone_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('domain_name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['database.id'], name=op.f('fk_company_database_id_database')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_company_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company'))
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_domain_name'), ['domain_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_domain_name'))

    op.drop_table('company')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_phone_no'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_technical_name'))
        batch_op.drop_index(batch_op.f('ix_module_official_name'))
        batch_op.drop_index(batch_op.f('ix_module_bp_name'))

    op.drop_table('module')
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_name'))

    op.drop_table('database')
    # ### end Alembic commands ###
