"""empty message

Revision ID: 439dff5b4f54
Revises: 72a314ca41a9
Create Date: 2022-01-17 19:55:27.274411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439dff5b4f54'
down_revision = '72a314ca41a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_group_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_group_slug'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
