"""empty message

Revision ID: 49a2d116a21e
Revises: 7b5f7b8be08b
Create Date: 2022-04-03 15:45:24.206639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a2d116a21e'
down_revision = '7b5f7b8be08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activity_lead_id_lead', type_='foreignkey')
        batch_op.drop_column('lead_id')

    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_lead_activity_lead_id_lead'), 'lead', ['lead_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lead_activity_lead_id_lead'), type_='foreignkey')
        batch_op.drop_column('lead_id')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_activity_lead_id_lead', 'lead', ['lead_id'], ['id'])

    # ### end Alembic commands ###
