"""empty message

Revision ID: 50c573ec1d35
Revises: f47165f11118
Create Date: 2021-10-02 18:49:14.310547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c573ec1d35'
down_revision = 'f47165f11118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('referred_by', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=15), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_lead_company_id_company')),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_lead_partner_id_partner')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lead_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead'))
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_priority'))
        batch_op.drop_index(batch_op.f('ix_lead_name'))

    op.drop_table('lead')
    # ### end Alembic commands ###
