"""empty message

Revision ID: 55a7c8d64f78
Revises: 3a2d6984adee
Create Date: 2022-01-24 15:50:49.777966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a7c8d64f78'
down_revision = '3a2d6984adee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_model_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_model_slug'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
