"""empty message

Revision ID: 564ad9e17d3b
Revises: e11a320d8037
Create Date: 2021-09-29 16:10:30.026454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564ad9e17d3b'
down_revision = 'e11a320d8037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_alphabetic_code', sa.String(length=60), nullable=True))
        batch_op.drop_index('ix_country_currency_aplhabetic_code')
        batch_op.create_index(batch_op.f('ix_country_currency_alphabetic_code'), ['currency_alphabetic_code'], unique=False)
        batch_op.drop_column('currency_aplhabetic_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_aplhabetic_code', sa.VARCHAR(length=60), nullable=True))
        batch_op.drop_index(batch_op.f('ix_country_currency_alphabetic_code'))
        batch_op.create_index('ix_country_currency_aplhabetic_code', ['currency_aplhabetic_code'], unique=False)
        batch_op.drop_column('currency_alphabetic_code')

    # ### end Alembic commands ###
