"""empty message

Revision ID: 57aa9994ff31
Revises: 40bcc0e69b8b
Create Date: 2022-02-16 17:07:51.877439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57aa9994ff31'
down_revision = '40bcc0e69b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
