"""empty message

Revision ID: 5aa3d25c6783
Revises: b2a1254d9c0a
Create Date: 2022-04-01 13:00:32.606529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa3d25c6783'
down_revision = 'b2a1254d9c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_team', schema=None) as batch_op:
        batch_op.drop_constraint('fk_partner_team_model_id_module', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_partner_team_model_id_model'), 'model', ['model_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_partner_team_model_id_model'), type_='foreignkey')
        batch_op.create_foreign_key('fk_partner_team_model_id_module', 'module', ['model_id'], ['id'])

    # ### end Alembic commands ###
