"""empty message

Revision ID: 5b75a90fb02d
Revises: c4537764373b
Create Date: 2022-04-18 01:10:16.160150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b75a90fb02d'
down_revision = 'c4537764373b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_purchase_vendor_id_partner'), 'partner', ['vendor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_purchase', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_purchase_vendor_id_partner'), type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
