"""empty message

Revision ID: 6ef4c4f7e3cd
Revises: a8174586c7de
Create Date: 2022-03-19 22:05:37.776280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ef4c4f7e3cd'
down_revision = 'a8174586c7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_type',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_activity_type_model_id_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_type'))
    )
    with op.batch_alter_table('activity_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_type_name'), ['name'], unique=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_activity_type_activity_type'), 'activity_type', ['type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_type_activity_type'), type_='foreignkey')
        batch_op.drop_column('type')

    with op.batch_alter_table('activity_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_type_name'))

    op.drop_table('activity_type')
    # ### end Alembic commands ###
