"""empty message

Revision ID: 728de5c8eae1
Revises: 7d2a9b028b85
Create Date: 2021-09-29 16:06:47.216833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728de5c8eae1'
down_revision = '7d2a9b028b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('currency_code', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_country_currency_code'), ['currency_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_currency_name'), ['currency_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_languages'), ['languages'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_languages'))
        batch_op.drop_index(batch_op.f('ix_country_currency_name'))
        batch_op.drop_index(batch_op.f('ix_country_currency_code'))
        batch_op.drop_column('languages')
        batch_op.drop_column('currency_code')
        batch_op.drop_column('currency_name')

    # ### end Alembic commands ###
