"""empty message

Revision ID: 7b5f7b8be08b
Revises: 5aa3d25c6783
Create Date: 2022-04-02 20:45:25.455146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b5f7b8be08b'
down_revision = '5aa3d25c6783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_filters',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_filters'))
    )
    with op.batch_alter_table('purchase_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_filters_index'), ['index'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_filters_name'), ['name'], unique=True)

    op.create_table('purchase_status',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_status'))
    )
    with op.batch_alter_table('purchase_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_status_name'), ['name'], unique=True)

    op.create_table('purchase',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('vendor', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('representative', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total', sa.String(length=120), nullable=True),
    sa.Column('status', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['representative'], ['users.id'], name=op.f('fk_purchase_representative_users')),
    sa.ForeignKeyConstraint(['status'], ['purchase_status.id'], name=op.f('fk_purchase_status_purchase_status')),
    sa.ForeignKeyConstraint(['vendor'], ['partner.id'], name=op.f('fk_purchase_vendor_partner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase'))
    )
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_total'), ['total'], unique=False)

    op.create_table('lead_activity',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['activity.id'], name=op.f('fk_lead_activity_id_activity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_activity'))
    )
    op.create_table('purchase_activity',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('purchase_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['activity.id'], name=op.f('fk_purchase_activity_id_activity')),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], name=op.f('fk_purchase_activity_purchase_id_purchase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_activity'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_activity')
    op.drop_table('lead_activity')
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_total'))
        batch_op.drop_index(batch_op.f('ix_purchase_reference'))

    op.drop_table('purchase')
    with op.batch_alter_table('purchase_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_status_name'))

    op.drop_table('purchase_status')
    with op.batch_alter_table('purchase_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_filters_name'))
        batch_op.drop_index(batch_op.f('ix_purchase_filters_index'))

    op.drop_table('purchase_filters')
    # ### end Alembic commands ###
