"""empty message

Revision ID: 7d2a9b028b85
Revises: ffe45c1543e4
Create Date: 2021-09-29 15:32:35.107966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2a9b028b85'
down_revision = 'ffe45c1543e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geonameid', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_city_geonameid'), ['geonameid'])

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_constraint('uq_country_geonameid', type_='unique')
        batch_op.drop_column('geonameid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geonameid', sa.INTEGER(), nullable=True))
        batch_op.create_unique_constraint('uq_country_geonameid', ['geonameid'])

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_city_geonameid'), type_='unique')
        batch_op.drop_column('geonameid')

    # ### end Alembic commands ###
