"""empty message

Revision ID: 8eb42e178469
Revises: 439dff5b4f54
Create Date: 2022-01-18 15:22:24.932887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb42e178469'
down_revision = '439dff5b4f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_group_module_id_module'), 'module', ['module_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_group_module_id_module'), type_='foreignkey')
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###
