"""empty message

Revision ID: 8f55a2f7e9f5
Revises: 
Create Date: 2021-09-27 11:14:00.024510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f55a2f7e9f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_category'))
    )
    with op.batch_alter_table('company_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_category_name'), ['name'], unique=False)

    op.create_table('database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database'))
    )
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_name'), ['name'], unique=False)

    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technical_name', sa.String(length=128), nullable=True),
    sa.Column('official_name', sa.String(length=128), nullable=True),
    sa.Column('bp_name', sa.String(length=128), nullable=True),
    sa.Column('installed_version', sa.String(length=60), nullable=True),
    sa.Column('auto_install', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.String(length=350), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module'))
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_bp_name'), ['bp_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_official_name'), ['official_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_technical_name'), ['technical_name'], unique=False)

    op.create_table('partner_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_title'))
    )
    with op.batch_alter_table('partner_title', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_title_name'), ['name'], unique=False)

    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('domain_name', sa.String(length=120), nullable=True),
    sa.Column('report_header', sa.Text(), nullable=True),
    sa.Column('report_footer', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('street2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_address', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('mobile_no', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['company_category.id'], name=op.f('fk_company_category_id_company_category')),
    sa.ForeignKeyConstraint(['database_id'], ['database.id'], name=op.f('fk_company_database_id_database')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company'))
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_domain_name'), ['domain_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_mobile_no'), ['mobile_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_website'), ['website'], unique=False)

    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_individual', sa.Boolean(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('phone_no', sa.String(length=120), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_partner_company_id_company')),
    sa.ForeignKeyConstraint(['parent_id'], ['partner.id'], name=op.f('fk_partner_parent_id_partner')),
    sa.ForeignKeyConstraint(['title_id'], ['partner_title.id'], name=op.f('fk_partner_title_id_partner_title')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner'))
    )
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_partner_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_phone_no'), ['phone_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_website'), ['website'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_user_company_id_company')),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_user_partner_id_partner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))

    op.drop_table('user')
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_website'))
        batch_op.drop_index(batch_op.f('ix_partner_phone_no'))
        batch_op.drop_index(batch_op.f('ix_partner_name'))
        batch_op.drop_index(batch_op.f('ix_partner_email'))

    op.drop_table('partner')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_website'))
        batch_op.drop_index(batch_op.f('ix_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_mobile_no'))
        batch_op.drop_index(batch_op.f('ix_company_email'))
        batch_op.drop_index(batch_op.f('ix_company_domain_name'))

    op.drop_table('company')
    with op.batch_alter_table('partner_title', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_title_name'))

    op.drop_table('partner_title')
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_technical_name'))
        batch_op.drop_index(batch_op.f('ix_module_official_name'))
        batch_op.drop_index(batch_op.f('ix_module_bp_name'))

    op.drop_table('module')
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_name'))

    op.drop_table('database')
    with op.batch_alter_table('company_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_category_name'))

    op.drop_table('company_category')
    # ### end Alembic commands ###
