"""empty message

Revision ID: 91298275f105
Revises: 01a2236fa4c9
Create Date: 2021-10-14 10:16:17.513636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91298275f105'
down_revision = '01a2236fa4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['partner.id'], name=op.f('fk_team_member_member_partner')),
    sa.ForeignKeyConstraint(['team'], ['team.id'], name=op.f('fk_team_member_team_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_member'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_team_id_team', type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_users_team_id_team', 'team', ['team_id'], ['id'])

    op.drop_table('team_member')
    # ### end Alembic commands ###
