"""empty message

Revision ID: 93685df693ed
Revises: 50c573ec1d35
Create Date: 2021-10-02 20:29:15.032389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93685df693ed'
down_revision = '50c573ec1d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['partner.id'], name=op.f('fk_organization_id_partner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(length=15), nullable=True))
        batch_op.create_index(batch_op.f('ix_lead_stage'), ['stage'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_stage'))
        batch_op.drop_column('stage')

    op.drop_table('organization')
    op.drop_table('team')
    # ### end Alembic commands ###
