"""empty message

Revision ID: 9b01443be4ac
Revises: 3e139417df1f
Create Date: 2022-03-19 22:32:52.554172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b01443be4ac'
down_revision = '3e139417df1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_activity_assigned_to_partner'), 'partner', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_assigned_to_partner'), type_='foreignkey')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
