"""empty message

Revision ID: a34e17fce54d
Revises: fa5667a7c6ad
Create Date: 2022-05-25 10:41:47.198936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34e17fce54d'
down_revision = 'fa5667a7c6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute_value', schema=None) as batch_op:
        batch_op.drop_index('ix_attribute_value_name')
        batch_op.create_index(batch_op.f('ix_attribute_value_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attribute_value_name'))
        batch_op.create_index('ix_attribute_value_name', ['name'], unique=False)

    # ### end Alembic commands ###
