"""empty message

Revision ID: a3dd2d635900
Revises: 91298275f105
Create Date: 2021-10-14 11:43:18.763860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3dd2d635900'
down_revision = '91298275f105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_team_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_token'))
        batch_op.drop_column('token')

    # ### end Alembic commands ###
