"""empty message

Revision ID: a64ec16a7f2a
Revises: 59864d7e6764
Create Date: 2022-05-16 12:37:08.927601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64ec16a7f2a'
down_revision = '59864d7e6764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promo_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('promo_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('promo_end')
        batch_op.drop_column('promo_start')
        batch_op.drop_column('promo')

    # ### end Alembic commands ###
