"""empty message

Revision ID: a9cc9a274e27
Revises: a346a1f5600a
Create Date: 2022-04-30 00:57:29.379535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9cc9a274e27'
down_revision = 'a346a1f5600a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_sub_category_id_product_category', type_='foreignkey')
        batch_op.drop_column('sub_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category_id', postgresql.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_product_sub_category_id_product_category', 'product_category', ['sub_category_id'], ['id'])

    # ### end Alembic commands ###
