"""empty message

Revision ID: a9e574ec7fab
Revises: a9cc9a274e27
Create Date: 2022-05-03 10:41:50.853411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9e574ec7fab'
down_revision = 'a9cc9a274e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_type_id_product_type'), 'product_type', ['type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_type_id_product_type'), type_='foreignkey')
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
