"""empty message

Revision ID: aa3fc14b3efb
Revises: 46a58b2c3049
Create Date: 2021-09-24 22:02:55.334776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3fc14b3efb'
down_revision = '46a58b2c3049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_title'))
    )
    with op.batch_alter_table('contact_title', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_title_name'), ['name'], unique=False)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_contact_title_id_contact_title'), 'contact_title', ['title_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contact_title_id_contact_title'), type_='foreignkey')
        batch_op.drop_column('title_id')

    with op.batch_alter_table('contact_title', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_title_name'))

    op.drop_table('contact_title')
    # ### end Alembic commands ###
