"""empty message

Revision ID: ad8069878fa4
Revises: 92598649788c
Create Date: 2022-04-18 18:46:53.395887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad8069878fa4'
down_revision = '92598649788c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uom_category',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uom_category'))
    )
    op.create_table('uom',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['uom_category.id'], name=op.f('fk_uom_category_id_uom_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uom'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uom')
    op.drop_table('uom_category')
    # ### end Alembic commands ###
