"""empty message

Revision ID: b2a1254d9c0a
Revises: 16c893ebff11
Create Date: 2022-03-21 21:23:51.971078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a1254d9c0a'
down_revision = '16c893ebff11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_partner_team_model_id_module'), 'module', ['model_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_partner_team_model_id_module'), type_='foreignkey')
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###
