"""empty message

Revision ID: b7ebf1e8e077
Revises: f0268d1405ad
Create Date: 2021-10-04 12:14:18.989670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ebf1e8e077'
down_revision = 'f0268d1405ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_partner_email')
        batch_op.create_index(batch_op.f('ix_lead_partner_email'), ['partner_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_partner_email'))
        batch_op.create_index('ix_lead_partner_email', ['partner_email'], unique=False)

    # ### end Alembic commands ###
