"""empty message

Revision ID: c002759539a7
Revises: 3ce2db8587c0
Create Date: 2022-01-27 10:24:49.325262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c002759539a7'
down_revision = '3ce2db8587c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('created_on')

    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
