"""empty message

Revision ID: c4537764373b
Revises: 57d55714e1e9
Create Date: 2022-04-18 01:08:52.075882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4537764373b'
down_revision = '57d55714e1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_purchase', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_purchase_vendor_id_partner', type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', postgresql.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_product_purchase_vendor_id_partner', 'partner', ['vendor_id'], ['id'])

    # ### end Alembic commands ###
