"""empty message

Revision ID: d7c5b068d91a
Revises: bb1ca9e0ea0d
Create Date: 2022-05-25 17:55:26.912338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7c5b068d91a'
down_revision = 'bb1ca9e0ea0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_parent_id_product'), 'product', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_parent_id_product'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
