"""empty message

Revision ID: dcbf4b2b6dcc
Revises: e6b7c41c6dde
Create Date: 2022-05-07 22:27:08.091468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbf4b2b6dcc'
down_revision = 'e6b7c41c6dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute_value', schema=None) as batch_op:
        batch_op.drop_index('ix_attribute_value_name')
        batch_op.create_index(batch_op.f('ix_attribute_value_name'), ['name'], unique=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_product_name'), ['name'])

    with op.batch_alter_table('product_attribute', schema=None) as batch_op:
        batch_op.drop_index('ix_product_attribute_name')
        batch_op.create_index(batch_op.f('ix_product_attribute_name'), ['name'], unique=True)

    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.drop_index('ix_product_category_name')
        batch_op.create_index(batch_op.f('ix_product_category_name'), ['name'], unique=True)

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_uom_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_uom_name'), type_='unique')

    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category_name'))
        batch_op.create_index('ix_product_category_name', ['name'], unique=False)

    with op.batch_alter_table('product_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_attribute_name'))
        batch_op.create_index('ix_product_attribute_name', ['name'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_product_name'), type_='unique')

    with op.batch_alter_table('attribute_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attribute_value_name'))
        batch_op.create_index('ix_attribute_value_name', ['name'], unique=False)

    # ### end Alembic commands ###
