"""empty message

Revision ID: e11a320d8037
Revises: 728de5c8eae1
Create Date: 2021-09-29 16:09:18.498771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11a320d8037'
down_revision = '728de5c8eae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_aplhabetic_code', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('currency_numeric_code', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_country_currency_code')
        batch_op.create_index(batch_op.f('ix_country_currency_aplhabetic_code'), ['currency_aplhabetic_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_currency_numeric_code'), ['currency_numeric_code'], unique=False)
        batch_op.drop_column('currency_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.VARCHAR(length=60), nullable=True))
        batch_op.drop_index(batch_op.f('ix_country_currency_numeric_code'))
        batch_op.drop_index(batch_op.f('ix_country_currency_aplhabetic_code'))
        batch_op.create_index('ix_country_currency_code', ['currency_code'], unique=False)
        batch_op.drop_column('currency_numeric_code')
        batch_op.drop_column('currency_aplhabetic_code')

    # ### end Alembic commands ###
