"""empty message

Revision ID: e3586de09e5e
Revises: d7c5b068d91a
Create Date: 2022-05-25 18:02:16.814757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3586de09e5e'
down_revision = 'd7c5b068d91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_name', ['name'])

    # ### end Alembic commands ###
