"""empty message

Revision ID: e6b7c41c6dde
Revises: ba3517795870
Create Date: 2022-05-06 00:55:02.245371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6b7c41c6dde'
down_revision = 'ba3517795870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_attribute_value',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('attribute_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('attribute_value_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['product_attribute.id'], name=op.f('fk_product_attribute_value_attribute_id_product_attribute')),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_value.id'], name=op.f('fk_product_attribute_value_attribute_value_id_attribute_value')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_attribute_value_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_attribute_value'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_attribute_value')
    # ### end Alembic commands ###
