"""empty message

Revision ID: e9a24861991c
Revises: e9147452434c
Create Date: 2021-10-06 14:28:14.352297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a24861991c'
down_revision = 'e9147452434c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_lead_plan_id_recurring_plan'), 'recurring_plan', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lead_plan_id_recurring_plan'), type_='foreignkey')
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###
