"""empty message

Revision ID: ecb741ce4368
Revises: a9e574ec7fab
Create Date: 2022-05-03 10:48:28.113098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ecb741ce4368'
down_revision = 'a9e574ec7fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uom_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_uom_id_uom'), 'uom', ['uom_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_uom_id_uom'), type_='foreignkey')
        batch_op.drop_column('uom_id')

    # ### end Alembic commands ###
