"""empty message

Revision ID: f0268d1405ad
Revises: ce395270fdfb
Create Date: 2021-10-04 12:11:41.960935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0268d1405ad'
down_revision = 'ce395270fdfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('partner_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('partner_currency', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_lead_partner_currency'), ['partner_currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_partner_email'), ['partner_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_lead_partner_name'), ['partner_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_partner_name'))
        batch_op.drop_index(batch_op.f('ix_lead_partner_email'))
        batch_op.drop_index(batch_op.f('ix_lead_partner_currency'))
        batch_op.drop_column('partner_currency')
        batch_op.drop_column('partner_email')
        batch_op.drop_column('partner_name')

    # ### end Alembic commands ###
