"""empty message

Revision ID: f1111f0feba7
Revises: 5f3a736c65e1
Create Date: 2022-05-09 12:07:59.524056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1111f0feba7'
down_revision = '5f3a736c65e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_category_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
