"""empty message

Revision ID: f47165f11118
Revises: 304783f67d5e
Create Date: 2021-09-30 19:12:31.540570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47165f11118'
down_revision = '304783f67d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_partner_city_id')
        batch_op.drop_index('ix_partner_country_id')
        batch_op.create_index(batch_op.f('ix_partner_tax_id'), ['tax_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_partner_country_id_country'), 'country', ['country_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_partner_city_id_city'), 'city', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_partner_city_id_city'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_partner_country_id_country'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_partner_tax_id'))
        batch_op.create_index('ix_partner_country_id', ['country_id'], unique=False)
        batch_op.create_index('ix_partner_city_id', ['city_id'], unique=False)
        batch_op.drop_column('tax_id')

    # ### end Alembic commands ###
