"""empty message

Revision ID: fa5667a7c6ad
Revises: a64ec16a7f2a
Create Date: 2022-05-16 12:46:02.015203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5667a7c6ad'
down_revision = 'a64ec16a7f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('promo_price')

    # ### end Alembic commands ###
