"""empty message

Revision ID: fb9f9ce93c45
Revises: c665d3feea6e
Create Date: 2022-02-20 17:38:22.421149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9f9ce93c45'
down_revision = 'c665d3feea6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAccess',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], name=op.f('fk_UserAccess_access_id_access')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_UserAccess_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'access_id', name=op.f('pk_UserAccess'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserAccess')
    # ### end Alembic commands ###
