"""empty message

Revision ID: ffe45c1543e4
Revises: 4f66eaf0bb9a
Create Date: 2021-09-29 15:14:49.216266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe45c1543e4'
down_revision = '4f66eaf0bb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currency'))
    )
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currency_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_currency_name'), ['name'], unique=True)

    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('geonameid', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('calling_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name=op.f('fk_country_currency_id_currency')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country')),
    sa.UniqueConstraint('geonameid', name=op.f('uq_country_geonameid'))
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_calling_code'), ['calling_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_country_name'), ['name'], unique=True)

    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_city_country_id_country')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city'))
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_name'))

    op.drop_table('city')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_name'))
        batch_op.drop_index(batch_op.f('ix_country_code'))
        batch_op.drop_index(batch_op.f('ix_country_calling_code'))

    op.drop_table('country')
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currency_name'))
        batch_op.drop_index(batch_op.f('ix_currency_code'))

    op.drop_table('currency')
    # ### end Alembic commands ###
