# Install the app  without become sudo
- hosts: local
  connection: local
  tasks:
    - name: Clone repo
      git:
        repo: "https://{{ gitlabuser | urlencode }}:{{ gitlabpassword | urlencode }}@gitlab.com/{{ gitlabuser }}/{{ app_name }}"
        dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
        update: yes # Does a git pull if the repo already exists

    - name: Install virtualenv via pip
      pip:
        name: virtualenv
        executable: pip3

    - name: Install Module
      pip:
        requirements: /home/{{ ansible_ssh_user }}/{{ app_name }}/requirements.txt
        virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/venv
        virtualenv_python: python3.8

- hosts: local
  connection: local
  become: yes
  become_user: root
  roles:
    - packages-and-configurations
