---
# handlers file for packages-and-configurations
- name: Restart Systemd Service
  systemd:
    name: "{{ app_name }}.service"
    state: restarted
    enabled: yes

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
